"""Add public sharing fields

Revision ID: 1a7936716e0c
Revises: 
Create Date: 2025-05-19 05:00:00.711049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7936716e0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('share_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allow_comments', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.create_unique_constraint(None, ['share_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('allow_comments')
        batch_op.drop_column('view_count')
        batch_op.drop_column('slug')
        batch_op.drop_column('share_id')
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
